import type { Metadata } from "next";
import { useMemo } from "react";
import { DM_Sans, DM_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { createNoise2D } from "simplex-noise";
import NoiseBackground from "./components/NoiseBackground";
import Header from "./components/Header";
import Footer from "./components/Footer";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"], // or ["300", "400", "500"] for all available weights
});
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // or ["300", "400", "500"] for all available weights
});
const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400"], // or ["300", "400", "500"] for all available weights
});

export const metadata: Metadata = {
  title: "Léo COQUET",
  description: "Generated by Léo COQUET",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Generate a new seed and noise function on each render
  const noise2D = useMemo(() => {
    const randomSeed = Math.random() * 10000;
    function seededRandom() {
      let x = Math.sin(randomSeed + Math.random()) * 10000;
      return x - Math.floor(x);
    }
    return createNoise2D(seededRandom);
  }, []); // empty deps = run once per client-side load

  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${dmSans.variable} ${dmMono.variable} antialiased`}>
        <NoiseBackground/>
        {/* Main content */}
        <Header />
        <div className="flex items-center justify-center">
          {children}
        </div>
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}